server:
  applicationConnectors:
  - type: http
    port: 9090
    bindHost: 0.0.0.0
  adminConnectors:
  - type: http
    port: 9091
    bindHost: 0.0.0.0

swagger:
  resourcePackage: it.unimore.dipi.iot.http.api.resources

#logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
#  level: INFO